added error handling
Signed-off-by Piotr Danecki <piotr.a.danecki@gmail.com>

diff --git a/pmake b/pmake
--- a/pmake
+++ b/pmake
@@ -10,15 +10,30 @@ dirname="$(basename $wholedir)"
 
 if [ -f go ]
 then
-rm $dirname
+    if [ -f $dirname ]
+    then
+        rm $dirname
+    fi
     echo -e "[] ${CYAN}Build: Starting${NOCOLOR}"
-go build -o $dirname main.go
+    go build -o $dirname main.go
+    
+    if (( $? > 0 ))
+    then
+        echo -e "[$dirname] ${RED}Build: Failed${NOCOLOR}"
+        exit 1
+    fi
+
     echo -e "[$dirname] ${CYAN}Build: Done${NOCOLOR}"
 else
 if [ -f "build/Makefile" ]; then
     echo -e "[] ${CYAN}Build: Starting${NOCOLOR}"
     cd build
     make -j `nproc`
+    if (( $? > 0 ))
+    then
+        echo -e "[$dirname] ${RED}Build: Failed${NOCOLOR}"
+        exit 1
+    fi
     cd ..
     echo -e "[$dirname] ${CYAN}Build: Done${NOCOLOR}"
 else 
@@ -30,6 +45,11 @@ else
         echo -e "[$dirname] ${CYAN}Build: Starting${NOCOLOR}"
         cd build
         make -j `nproc`
+        if (( $? > 0 ))
+        then
+            echo -e "[$dirname] ${RED}Build: Failed${NOCOLOR}"
+            exit 1
+        fi
         cd ..
         echo -e "[$dirname] ${CYAN}Build: Done${NOCOLOR}"
     fi
diff --git a/pnewrust b/pnewrust
--- a/pnewrust
+++ b/pnewrust
@@ -19,6 +19,12 @@ else
     echo -e "[$name] ${CYAN} Creating package: Starting${NOCOLOR}"
     echo -e "[$name] ${CYAN} Creating cargo package${NOCOLOR}"
     cargo new $name
+
+    if (( $? > 0 ))
+    then
+        echo -e "[$name] ${RED} Creating package: FAILED${NOCOLOR}"
+        exit
+    fi
     
     echo -e "[$name] ${CYAN} Entering directory${NOCOLOR}"
     cd $name/src
diff --git a/prun b/prun
--- a/prun
+++ b/prun
@@ -19,11 +19,21 @@ fi
 if [ -f rust ]
 then 
     cargo run
+    if (( $? > 0 ))
+    then
+        echo -e "[$dirname] ${RED}Run: FAILED${NOCOLOR}"
+        exit
+    fi
     echo -e "[$dirname] ${CYAN}Run: Done${NOCOLOR}"
     exit 
 fi
 
 pmake
+
+if (( $? > 0 ))
+then
+    exit
+fi
 if [ -z $1 ]
 then
     filename=$dirname
